---
title: "AMB - Sustainability"
author: "inLab-CARNET-UPC"
date: \today
output:
  word_document:
    toc: no
    toc_depth: '4'
  html_document:
    toc: no
    toc_depth: '4'
  pdf_document:
    latex_engine: pdflatex
    number_sections: yes
    toc_depth: 4
    toc: yes
geometry: left=1.5cm,right=1.5cm,top=1.0cm,bottom=1.0cm
fontsize: 10pt
subtitle: 'Summaries EMIT Data'
classoption: a4paper
editor_options: 
  chunk_output_type: console
---
```{r, include=FALSE, echo=FALSE}
# Load Required Packages: to be increased over the course
options(contrasts=c("contr.treatment","contr.treatment"))
requiredPackages <- c("TraMineR","runner","lubridate","hms","missMDA","effects","FactoMineR","car","factoextra","RColorBrewer","ggplot2","dplyr","ggmap","ggthemes","knitr","chemometrics","rpart","ROCR","corrr","readxl","RColorBrewer","ggplot2","corrplot","plotly","xlsx","reshape2","scales","stargazer","kableExtra","AER","MASS","lattice")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(requiredPackages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
#verify they are loaded
search()

```

# Carregar dades completes 

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()
# Clean workspace
rm(list=ls())

setwd("C:/Users/lmontero/Dropbox/MEU_PROJECTINLAB/DADES/SUSTAINABILITY/APLICACIO-FRAGMENTATION/1.2 - PREPARATION")
pathfile<-"C:/Users/lmontero/Dropbox/MEU_PROJECTINLAB/DADES/SUSTAINABILITY/APLICACIO-FRAGMENTATION/1.2 - PREPARATION/"

load(paste0(pathfile,"1819EMEF_v3.RData"))

```

# Mètodes útils i càlculs de KPIs
```{r}
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], 
       q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }

mape<- function(matriu) {
  xx<-as.vector(abs((((matriu+t(matriu))/2)-matriu)/matriu));
  xy<-ifelse(!is.finite(xx),NA,xx);
  100*mean(xy,na.rm=T)
}
mape2<- function(matriu1,matriu2) {
  xx<-as.vector(abs(((matriu1)-matriu2)/((matriu1+matriu2)/2)));
  xy<-ifelse(!is.finite(xx),NA,xx);
  100*mean(xy,na.rm=T)
}

maxmape2<- function(matriu1,matriu2) {
  xx<-as.vector(abs(((matriu1)-matriu2)/((matriu1+matriu2)/2)));
  xy<-ifelse(!is.finite(xx),NA,xx);
  100*max(xy,na.rm=T)
}

R2<- function(matriu1,matriu2) {
  xx<-as.vector(matriu1);
  xy<-as.vector(matriu2);
  mm<-lm(xy~xx);
  lmm<-lm(log(xy+1)~log(xx+0.1));
  list( r1=100*summary(mm)$r.squared, r2=100*summary(lmm)$r.squared,
  p1={plot(xx,xy,main="Matriu 2 vs Matriu 1");abline(mm)},
  p2={plot(log(xx+0.1),log(xy+0.1),main="Matriu 2 vs Matriu 1 -logscale");abline(lmm)});
}

R2no0<- function(matriu1,matriu2) {
  xx<-as.vector(matriu1);
  ll<-which(xx>0)
  xy<-as.vector(matriu2);
  mm<-lm(xy[ll]~xx[ll])
  100*summary(mm)$r.squared
}

# SSIM Similarity Index by Wang

SSIM<- function(OD_Hist, OD_star, C1, C2, C3, alpha, beta, gamma)
  {
    mean_Hist = mean(OD_Hist);
    mean_star = mean(OD_star);
    dev_Hist = sd(OD_Hist);
    dev_star = sd(OD_star);
    cov = cov(OD_star, OD_Hist);
    L = (2*mean_Hist*mean_star + C1)/(mean_Hist^2 + mean_star^2 + C1);
    C = (2*dev_Hist*dev_star + C2)/(dev_Hist^2 + dev_star^2 + C2);
    S = (cov + C3)/(dev_star*dev_Hist + C3);
    SSIM = (L^alpha)*(C^beta)*(S^gamma)
}

MSSIM<- function(OD_Hist, OD_star, by_rows, by_cols, weight_Hist)
{
  #browser();
    dim_mat<-nrow(OD_Hist);
    ww<-1;
    Mat_Hist<-OD_Hist;
    Mat_star<-OD_star;
    if (!is.matrix(OD_Hist))
    { 
      dim_mat = round(sqrt(length(OD_Hist)),dig=0);
      Mat_Hist = matrix(OD_Hist, nrow=dim_mat, ncol=dim_mat,byrow=TRUE);
      Mat_star = matrix(OD_star, nrow=dim_mat, ncol=dim_mat,byrow=TRUE);
    }
    if (by_rows)
    {
        count = 0;
        SSIM_sum = 0;
        for (i in 1:dim_mat)
        { 
            if ( (max(Mat_Hist[i,]) > 0) | (max(Mat_star[i,]) > 0))
            { 
              if( weight_Hist )
              { 
                ww<-sum(Mat_Hist[i,])
                SSIM_sum = SSIM_sum + ww*SSIM(Mat_Hist[i,], Mat_star[i,], 1, 1, 1/2, 1, 1, 1);
                count = count + ww;
              }else{
                SSIM_sum = SSIM_sum + SSIM(Mat_Hist[i,], Mat_star[i,], 1, 1, 1/2, 1, 1, 1);
                count = count + 1;
              }
            }
         }
        MSSIM_row = min(1, SSIM_sum /count);
    }
    else
    {
      MSSIM_row = 0;
      }

    if (by_cols)
    { 
        count = 0;
        SSIM_sum = 0;
        for (j in 1:dim_mat )
          { 
            if ( (max(Mat_Hist[,j]) > 0) | (max(Mat_star[,j]) > 0))
            { 
              if (weight_Hist){ 
                ww<-sum(Mat_Hist[,j]);
                SSIM_sum = SSIM_sum + ww*SSIM(Mat_Hist[,j], Mat_star[,j], 1, 1, 1/2, 1, 1, 1);
                count = count + ww;
              }else{
                SSIM_sum = SSIM_sum + SSIM(Mat_Hist[,j], Mat_star[,j], 1, 1, 1/2, 1, 1, 1);
                count = count + 1;                
              }
            }
          }
          MSSIM_col = min(1, SSIM_sum /count);
          }
        else
        { 
            MMSIM_col = 0;
            }
list(MSSIM_row=MSSIM_row, MSSIM_col=MSSIM_col);
  }
```

# Comparativa turbulència i complexitat segons característiques individu

```{r}
attach(dftraminer)
noms <- names(dftraminer)[1:40];noms
summary(dftraminer[,noms])

plot(scomplexity~genere)
kruskal.test(nentropy~genere)
plot(scomplexity~year)
kruskal.test(scomplexity~year)
library(MASS)
boxcox(sqrt(turbulence)~genere+gedat+mun.res+year+nauto+nmot)
m1<-lm(I(sqrt(turbulence))~genere+gedat+mun.res+year+nauto+nmot+dia+per_hab_100m_m2+per_est_3r_grau+pa_bus+pa_metram+pa_tren)
m2<-step(m1,k=log(nrow(dftraminer)))
summary(m2)
Anova(m2)
plot(allEffects(m2))
m3<-lm(I(sqrt(turbulence)) ~ genere+gedat  + per_est_3r_grau + pa_bus  + pa_tren )
Anova(m3) 
plot(allEffects(m3))
plot(Effect(c("genere", "gedat"), m3))
plot(Effect(c("genere", "per_est_3r_grau"), m3))
plot(Effect(c("gedat", "per_est_3r_grau"), m3))
aov(m2)
par(mfrow=c(2,2))
plot(m2)
par(mfrow=c(1,1))

boxcox(nentropy~genere+gedat+mun.res+year+nauto+nmot)
m1<-lm(nentropy~genere+gedat+mun.res+year+nauto+nmot+dia+per_hab_100m_m2+per_est_3r_grau+pa_bus+pa_metram+pa_tren)
m2<-step(m1,k=log(nrow(dftraminer)))
summary(m2)
Anova(m2)
plot(allEffects(m2))
m3<-lm(nentropy ~ genere + gedat + nauto + per_hab_100m_m2 + pa_bus +per_est_3r_grau)
Anova(m3) 
plot(allEffects(m3))
plot(Effect(c("genere", "gedat"), m3))
plot(Effect(c("genere", "per_est_3r_grau"), m3))
plot(Effect(c("gedat", "per_est_3r_grau"), m3))
detach(dftraminer)
```
# Classificació

```{r}
noms <- names(dftraminer)
head(noms,45)
tail(noms)
noms <- names(dftraminer)[1:40];noms
head(dftraminer[,noms])
# Vull carregar característiques socioeconòmiques de mun.res - dis.res i està fet 1.2.3

ll<-which((dftraminer$mun.res=="Badalona")&(dftraminer$year==2018));length(ll)
subdftraminer<-dftraminer[ll,]
subdftraminer.seq <-dftraminer.seq[ll,]
submat <- seqsubm(subdftraminer.seq, method = "TRATE")
dist.om1 <- seqdist(subdftraminer.seq, method = "OM", indel = 1, sm = submat)
library(cluster)
clusterward1 <- agnes(dist.om1, diss = TRUE, method = "ward")
plot(clusterward1)
cl1.4 <- cutree(clusterward1, k = 4)
cl1.4fac <- factor(cl1.4, labels = paste("Cluster", 1:4))
eixdia <- sort(rep(0:32,60));eixdia
seqdplot(subdftraminer.seq, group = cl1.4fac,  withlegend = T, xlab="Day Time in hours", border = NA, title = "State distribution plot",xtlab=eixdia)
seqfplot(subdftraminer.seq, group = cl1.4fac,  withlegend = T, xlab="Day Time in hours", border = NA, title = "Representative patterns",xtlab=eixdia)

par(mfrow=c(1,3))
Boxplot(subdftraminer$entropy~cl1.4fac,col=heat.colors(4),main="Entropy by Cluster",ylab="Entropy",xlab="cluster")
Boxplot(subdftraminer$turbulence~cl1.4fac,col=heat.colors(4),main="Turbulence by Cluster",ylab="Turbulence",xlab="cluster")
Boxplot(subdftraminer$scomplexity~cl1.4fac,col=heat.colors(4),main="Complexity by Cluster",ylab="Complexity",xlab="cluster")
par(mfrow=c(1,1))


noms
rednoms<-noms[c(3,8:40)]
subdftraminer$cl4 <- cl1.4fac
res.cat <- catdes(subdftraminer[,c("cl4",rednoms)],1)
res.cat$category
res.cat$quanti

# Observed cluster membership by day of the week (DOW)
table(subdftraminer$day)
plot(subdftraminer$dia,subdftraminer$cl4,col=heat.colors(5),main="Cluster distribution according to weekday")
tt <- table(subdftraminer$dia,subdftraminer$cl4)
chisq.test(tt)
```


```{r}
res.kmean <- kmeans( dist.om1, 6)
res.kmean$betweenss/res.kmean$totss
res.kmean$cluster <- factor(res.kmean$cluster, labels = paste("Cluster", 1:6))
seqdplot(subdftraminer.seq, group = res.kmean$cluster, border = NA)
seqfplot(subdftraminer.seq, group = res.kmean$cluster, border = NA)
seqmtplot(subdftraminer.seq, group = res.kmean$cluster)

subdftraminer.seqe <- seqecreate(subdftraminer.seq)
fsubseq <- seqefsub(subdftraminer.seqe, pmin.support = 0.05)
plot(fsubse<-q[1:15], col = "cyan")

discr <- seqecmpgroup(fsubseq, group =as.numeric( dftraminer$genere[ll]))
plot(discr[1:6])
str(discr)
```

# Classificació usant variables actives per PCA els valors numèrics de l'alfabet

```{r}
ll<-which(dftraminer$year==2018)
noms
suplecat <- noms[c(16,17,24,26:30)];length(suplecat)
suplenum <- noms[c(9,10,11,15,22,23)];length(suplenum)
actinum<-names(dftraminer)[41:2005]
res.pca <- PCA(dftraminer[,c(suplecat,suplenum,actinum)],quali.sup=1:8,quanti.sup=9:14,graph=F,ncp=72) #
summary(res.pca)
res.pca$eig[,1:3]
# res.pca$eig[,1:3]
res.hcpc <- HCPC( res.pca, nb.clust=10, graph=F)
res.hcpc$call$t$within[1:15]
(res.hcpc$call$t$within[1]-res.hcpc$call$t$within[10])/res.hcpc$call$t$within[1]
dftraminer$hclu<-res.hcpc$data.clust$clust
# levels(dftraminer$estudis)<-c("None","Basic","Secondary","Bachelor","Other","Other","Other")
# levels(dftraminer$activitat)<-c("Active","Unemployed","Retired","Retired","Housekeeping","Student","Other","Other")
res.cat <- catdes( dftraminer[,c("hclu",suplecat,suplenum,"activitat","estudis","r_rm_pond_pob","ttrips","daytt","dia","mun.res")], 1, proba=0.005)
res.cat$test.chi2
res.cat$quanti.var
res.cat$category
res.cat$quanti
barplot(table(dftraminer$hclu),col=heat.colors(10),main="Cluster size - AMB area")
table(dftraminer$hclu,useNA="always")
str(dftraminer.seq)

ll <- which(dftraminer$hclu %in% c("3","4","5","6","7","8"));length(ll)
dev.off()
seqdplot(dftraminer.seq[ll,], group = factor(dftraminer$hclu[ll]),border = NA)

seqdplot(dftraminer.seq[ll,], group = factor(dftraminer$hclu[ll]),  with.legend = T, xlab="Day Time in hours", border = NA, main = "State distribution plot",xtlab=eixdia,ylab=NA,use.layout=T,rows=2,cols=3)

dt.melt <- melt(dftraminer[,c("id","year",actinum)], id = c(1,2), na.rm = FALSE)
#and cast
# dt.cast<-dcast( dt.melt, cbind(id,year) ~ value, fun = length, fill = 0 )
head(dt.melt)
tminact <- dt.melt %>% group_by(id,year) %>% mutate(sumaC=sum(value==1),sumaW=sum(value==5),sumaH=sum(value==2),sumaO=sum(value==3),sumaT=sum(value==4)) %>% filter(variable=="V1") %>% as.data.frame()

dftraminer$ttr <- tminact$sumaT/(tminact$sumaT+tminact$sumaC+tminact$sumaO+tminact$sumaW)

par(mfrow=c(1,4))
Boxplot(dftraminer$entropy[ll]~dftraminer$hclu[ll],col=heat.colors(6),main="Entropy by Cluster",ylab="Entropy",xlab="cluster")
Boxplot(dftraminer$turbulence[ll]~dftraminer$hclu[ll],col=heat.colors(6),main="Turbulence by Cluster",ylab="Turbulence",xlab="cluster")
Boxplot(dftraminer$scomplexity[ll]~dftraminer$hclu[ll],col=heat.colors(6),main="Complexity by Cluster",ylab="Complexity",xlab="cluster")
Boxplot(dftraminer$ttr[ll]~dftraminer$hclu[ll],col=heat.colors(6),main="TTR by Cluster",ylab="Total Travel Time ratio",xlab="cluster")
par(mfrow=c(1,1))

```

# Gràfics

```{r}
eixdia <- sort(rep(0:32,60));eixdia
seqstatd(dftraminer.seq)
seqdplot(dftraminer.seq,withlegend = T, cex.legend=0.75, xlab="Day Time in hours", border = NA, title = "Activity distribution at each time point",xtlab=eixdia, cex.axis=0.75)
seqiplot(dftraminer.seq, with.legend = T, cex.legend=0.75,main = "Sequence plot (3 first units)", border = NA, cex.axis=0.75, xlab="Day Time in hours", ylab="Unit",xtlab=eixdia, idxs=1:3)
seqfplot(dftraminer.seq, with.legend = T, cex.legend=0.75, xlab="Day Time in hours", border = NA, title = "Sequence frequency plot",xtlab=eixdia)
seqdplot(dftraminer.seq, withlegend = T, xlab="Day Time in hours", border = NA, title = "State distribution plot",xtlab=eixdia)
seqlegend(dftraminer.seq, fontsize = 1.3)
seqHtplot(dftraminer.seq, xlab="Day Time in hours", title = "Entropy index",xtlab=eixdia)
seqmtplot(dftraminer.seq, withlegend = T, xlab="Day Time in hours", border = NA, main = "Proportion of state by hour",xtlab=eixdia)
seqplot(dftraminer.seq, withlegend = T, xlab="Day Time in hours", border = NA, main = "Proportion of state by hour",xtlab=eixdia, type="ms")

# Sequence profile for groups defined by Min, Q1,Q2,Q3, Max turbulences

turb.group <- cut(dftraminer$turbulence, quantile(dftraminer$turbulence), include.lowest = T)
table(turb.group)
seqfplot(dftraminer.seq, group = turb.group, pbarw = TRUE)

```


# Guardar resultat

```{r}
pathfile <-"C:/Users/lmontero/Dropbox/MEU_PROJECTINLAB/DADES/SUSTAINABILITY/APLICACIO-FRAGMENTATION/1.2 - PREPARATION/"
# save(list=c("corresp","dfimp","dfpred","dfmo","dfmt","dfnom3OD","dfnomw","dfvalid","dfnom3taz","dfvalidtaz"), file = paste0(pathfile,"DataSources_v3.RData"))

save(list=c("dfmo","dfmt","dfmad","dfmadchain","dfmadlast","dftraminer","dftraminer.seq"), file = paste0(pathfile,"1819EMEF_v4.RData"))
```
